name: Send Weekly Menu

on:
  schedule:
    - cron: '0 23 * * 0'  # 매주 월요일 오전 8시 (KST)
  workflow_dispatch:     

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pillow pytesseract
          pip install python-dotenv

    - name: Run script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
      run: python notifier.py
